### ISSUE TITLE
Remove 2.0.0 Python 2 package from PyPI

### ISSUE THREAD

**Issue by adamantike** [adamchainz/django-modeldict#171]
`django-modeldict` 2.0.0 was uploaded to PyPI as a universal release (`django_modeldict_yplan-2.0.0-py2.py3-none-any.whl`), but it dropped support for Python 2. Please remove this wheel, and upload only a py3-specific wheel, to avoid breaking Python 2 installations.

Related error when trying to install the package from a Python 2 virtualenv:
```
$ pip install django-modeldict-yplan
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: http://localhost:3141/root/pypi/+simple/
Collecting django-modeldict-yplan
  Downloading http://localhost:3141/root/pypi/+f/f45/ba978634464b9/django_modeldict_yplan-2.0.0-py2.py3-none-any.whl
django-modeldict-yplan requires Python '>=3.4' but the running Python is 2.7.15
```

**Comment by adamantike** [comment]
Ping @adamchainz, as this is breaking Python 2 installations.

**Comment by adamchainz** [comment]
Sorry about this, missed one thing in my Python 2 deprecation plan! Removed now and uploaded a Python 3 only wheel.

Of course, this is a good point to say you should be pinning your requirements 😁 I recommend [`pip-tools`](https://github.com/jazzband/pip-tools) if you don't have anything in place apart from maybe an unpinned `requirements.txt`, or [`pipenv`](https://pipenv.readthedocs.io/en/latest/) if you have more time to set up.

**Comment by adamantike** [comment]
@adamchainz still getting the same error, probably because of PyPI having it cached/available somewhere else:

```
$ pip install --no-cache-dir django-modeldict-yplan
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting django-modeldict-yplan
  Downloading https://files.pythonhosted.org/packages/a6/0e/ef6d576ea0c2c606fd70e92e25c129f7715d3be1b45a14f3e2f79ae99858/django-modeldict-yplan-2.0.0.tar.gz
django-modeldict-yplan requires Python '>=3.4' but the running Python is 2.7.15
```

**Comment by adamantike** [comment]
This is using the latest pip version (`19.0.1`).

I agree that projects should use `pip-tools` or any other way to have pinned dependencies! However, that's not the case for shared libraries, which need flexible requirements, and that will start failing if they don't patch their own requirements.

That's also the reason I've filed adamchainz/gargoyle#230.
